services:
  - type: web
    name: salesdashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: sales-dashboard-db
    databaseName: sales_dashboard
    user: sales_dashboard_user
    plan: free
