services:
  - type: web
    name: salesdashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: sales-dashboard-db
    databaseName: sales_dashboard
    user: sales_dashboard_user
    plan: free
