services:
  - type: web
    name: salesdashboard
    env: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: sales-dashboard-db
          property: connectionString
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: sales-dashboard-db
    databaseName: sales_dashboard
    user: sales_dashboard_user
    plan: free
